# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/python/os_project/ui_pcb_simulator_panel.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_pcb_sp(object):
    def setupUi(self, pcb_sp):
        pcb_sp.setObjectName("pcb_sp")
        pcb_sp.resize(759, 498)
        self.gridLayoutWidget = QtWidgets.QWidget(pcb_sp)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 70, 681, 192))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_wakeup1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_wakeup1.setObjectName("btn_wakeup1")
        self.gridLayout.addWidget(self.btn_wakeup1, 1, 5, 1, 1)
        self.btn_block2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_block2.setObjectName("btn_block2")
        self.gridLayout.addWidget(self.btn_block2, 2, 4, 1, 1)
        self.btn_wakeup2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_wakeup2.setObjectName("btn_wakeup2")
        self.gridLayout.addWidget(self.btn_wakeup2, 2, 5, 1, 1)
        self.btn_block3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_block3.setObjectName("btn_block3")
        self.gridLayout.addWidget(self.btn_block3, 3, 4, 1, 1)
        self.btn_wakeup3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_wakeup3.setObjectName("btn_wakeup3")
        self.gridLayout.addWidget(self.btn_wakeup3, 3, 5, 1, 1)
        self.btn_block5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_block5.setObjectName("btn_block5")
        self.gridLayout.addWidget(self.btn_block5, 5, 4, 1, 1)
        self.btn_block4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_block4.setObjectName("btn_block4")
        self.gridLayout.addWidget(self.btn_block4, 4, 4, 1, 1)
        self.btn_wakeup4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_wakeup4.setObjectName("btn_wakeup4")
        self.gridLayout.addWidget(self.btn_wakeup4, 4, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.btn_create1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_create1.setObjectName("btn_create1")
        self.gridLayout.addWidget(self.btn_create1, 1, 2, 1, 1)
        self.btn_create2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_create2.setObjectName("btn_create2")
        self.gridLayout.addWidget(self.btn_create2, 2, 2, 1, 1)
        self.status3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status3.setText("")
        self.status3.setObjectName("status3")
        self.gridLayout.addWidget(self.status3, 3, 1, 1, 1)
        self.status1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status1.setText("")
        self.status1.setObjectName("status1")
        self.gridLayout.addWidget(self.status1, 1, 1, 1, 1)
        self.status2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status2.setText("")
        self.status2.setObjectName("status2")
        self.gridLayout.addWidget(self.status2, 2, 1, 1, 1)
        self.status5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status5.setText("")
        self.status5.setObjectName("status5")
        self.gridLayout.addWidget(self.status5, 5, 1, 1, 1)
        self.status4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.status4.setText("")
        self.status4.setObjectName("status4")
        self.gridLayout.addWidget(self.status4, 4, 1, 1, 1)
        self.btn_block1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_block1.setObjectName("btn_block1")
        self.gridLayout.addWidget(self.btn_block1, 1, 4, 1, 1)
        self.btn_schedule4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_schedule4.setObjectName("btn_schedule4")
        self.gridLayout.addWidget(self.btn_schedule4, 4, 3, 1, 1)
        self.btn_schedule5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_schedule5.setObjectName("btn_schedule5")
        self.gridLayout.addWidget(self.btn_schedule5, 5, 3, 1, 1)
        self.btn_wakeup5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_wakeup5.setObjectName("btn_wakeup5")
        self.gridLayout.addWidget(self.btn_wakeup5, 5, 5, 1, 1)
        self.btn_create4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_create4.setObjectName("btn_create4")
        self.gridLayout.addWidget(self.btn_create4, 4, 2, 1, 1)
        self.btn_create3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_create3.setObjectName("btn_create3")
        self.gridLayout.addWidget(self.btn_create3, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.btn_schedule1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_schedule1.setObjectName("btn_schedule1")
        self.gridLayout.addWidget(self.btn_schedule1, 1, 3, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 1, 0, 1, 1)
        self.btn_create5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_create5.setObjectName("btn_create5")
        self.gridLayout.addWidget(self.btn_create5, 5, 2, 1, 1)
        self.btn_schedule2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_schedule2.setObjectName("btn_schedule2")
        self.gridLayout.addWidget(self.btn_schedule2, 2, 3, 1, 1)
        self.btn_schedule3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_schedule3.setObjectName("btn_schedule3")
        self.gridLayout.addWidget(self.btn_schedule3, 3, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 4)
        self.label = QtWidgets.QLabel(pcb_sp)
        self.label.setGeometry(QtCore.QRect(270, 20, 321, 31))
        self.label.setObjectName("label")
        self.status_bar = QtWidgets.QPlainTextEdit(pcb_sp)
        self.status_bar.setGeometry(QtCore.QRect(30, 280, 701, 201))
        self.status_bar.setPlainText("")
        self.status_bar.setObjectName("status_bar")

        self.retranslateUi(pcb_sp)
        QtCore.QMetaObject.connectSlotsByName(pcb_sp)

    def retranslateUi(self, pcb_sp):
        _translate = QtCore.QCoreApplication.translate
        pcb_sp.setWindowTitle(_translate("pcb_sp", "PCB Simulator"))
        self.btn_wakeup1.setText(_translate("pcb_sp", "wakeup"))
        self.btn_block2.setText(_translate("pcb_sp", "block"))
        self.btn_wakeup2.setText(_translate("pcb_sp", "wakeup"))
        self.btn_block3.setText(_translate("pcb_sp", "block"))
        self.btn_wakeup3.setText(_translate("pcb_sp", "wakeup"))
        self.btn_block5.setText(_translate("pcb_sp", "block"))
        self.btn_block4.setText(_translate("pcb_sp", "block"))
        self.btn_wakeup4.setText(_translate("pcb_sp", "wakeup"))
        self.label_3.setText(_translate("pcb_sp", "not created"))
        self.label_2.setText(_translate("pcb_sp", "not created"))
        self.label_5.setText(_translate("pcb_sp", "not created"))
        self.btn_create1.setText(_translate("pcb_sp", "Terminate"))
        self.btn_create2.setText(_translate("pcb_sp", "Terminate"))
        self.btn_block1.setText(_translate("pcb_sp", "block"))
        self.btn_schedule4.setText(_translate("pcb_sp", "schedule"))
        self.btn_schedule5.setText(_translate("pcb_sp", "schedule"))
        self.btn_wakeup5.setText(_translate("pcb_sp", "wakeup"))
        self.btn_create4.setText(_translate("pcb_sp", "Terminate"))
        self.btn_create3.setText(_translate("pcb_sp", "Terminate"))
        self.label_4.setText(_translate("pcb_sp", "not created"))
        self.btn_schedule1.setText(_translate("pcb_sp", "schedule"))
        self.label_1.setText(_translate("pcb_sp", "not created"))
        self.btn_create5.setText(_translate("pcb_sp", "Terminate"))
        self.btn_schedule2.setText(_translate("pcb_sp", "schedule"))
        self.btn_schedule3.setText(_translate("pcb_sp", "schedule"))
        self.label_12.setText(_translate("pcb_sp", "PID"))
        self.label_13.setText(_translate("pcb_sp", "Status"))
        self.label_14.setText(_translate("pcb_sp", "Actions"))
        self.label.setText(_translate("pcb_sp", "PCB Simulator Panel"))

